# Generated by Django 4.2.5 on 2023-09-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone_umber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_umber',
            new_name='phone_number',
        ),
    ]
