# Generated by Django 4.2.7 on 2023-11-10 05:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('day', models.SmallIntegerField()),
                ('group', models.CharField(blank=True, max_length=50)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Daily Scheduler',
                'verbose_name_plural': 'Daily Schedulers',
                'db_table': 'shifts_daily_scheduler',
                'ordering': ['-created'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ShiftCategory',
        ),
        migrations.AlterModelTable(
            name='shiftcategory',
            table='shifts_shift_category',
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('daily_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.dailyscheduler')),
            ],
            options={
                'verbose_name': 'Scheduler',
                'verbose_name_plural': 'Schedulers',
                'ordering': ['-created'],
            },
        ),
    ]
