# Generated by Django 4.2.7 on 2023-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_dailyscheduler_rename_category_shiftcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyscheduler',
            name='day',
        ),
        migrations.AddField(
            model_name='dailyscheduler',
            name='day_of_the_week',
            field=models.SmallIntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default=1),
            preserve_default=False,
        ),
    ]
