# Generated by Django 4.2.7 on 2023-11-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_missinghours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingHours',
        ),
    ]
