# Generated by Django 4.2.7 on 2023-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_dailyscheduler_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscheduler',
            name='day_of_the_week',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1),
        ),
    ]
