# Generated by Django 4.2.7 on 2023-11-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_delete_missinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='missing_hours',
            field=models.ManyToManyField(to='shifts.scheduler'),
        ),
    ]
