# Generated by Django 4.2.7 on 2023-11-11 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_missing_missing_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Justification Category',
                'verbose_name_plural': 'Justification Categories',
                'db_table': 'shifts_justification_category',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Justifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='shifts/justificationsDocuments')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.justificationcategory')),
                ('missing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shifts.missing')),
            ],
            options={
                'verbose_name': 'Justification',
                'verbose_name_plural': 'Justifications',
                'ordering': ['-created'],
            },
        ),
    ]
