# Generated by Django 4.2.7 on 2023-11-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_justificationcategory_justifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Justifications',
            new_name='Justification',
        ),
    ]
