# Generated by Django 4.2.7 on 2023-11-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_dailyscheduler_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscheduler',
            name='day_of_the_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
