# Generated by Django 4.2.7 on 2023-11-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_dailyscheduler_day_of_the_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shiftcategory'),
        ),
    ]
