# Generated by Django 4.2.7 on 2023-11-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_alter_shift_shift_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
