# Generated by Django 4.2.7 on 2023-11-10 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_alter_shiftcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_vacations', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('has_assisted', models.PositiveSmallIntegerField(default=0)),
                ('daily_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.dailyscheduler')),
            ],
            options={
                'verbose_name': 'Assistance',
                'verbose_name_plural': 'Assistances',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_justified', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=50)),
                ('assistance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shifts.assistance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
