# Generated by Django 4.2.7 on 2023-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_alter_assistance_has_assisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='has_assisted',
            field=models.PositiveSmallIntegerField(choices=[(0, 'did not assist'), (1, 'assisted '), (2, 'assisted but left early'), (4, 'arrived late'), (5, 'arrived late and left early')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('daily_scheduler', 'date')},
        ),
    ]
